branch-defaults:
  main:
    environment: WebRegalitos-dev
    group_suffix: null
deploy:
  artifact: target/mytodo-1.0-SNAPSHOT.jar
global:
  application_name: WebRegalitos
  branch: null
  default_ec2_keyname: null
  default_platform: Corretto 21 running on 64bit Amazon Linux 2023
  default_region: eu-west-3
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
